# Generated by Django 4.2.7 on 2026-07-21 18:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('cost_optimizer', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='uploadedreport',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='recommendation',
            name='record',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recommendations', to='cost_optimizer.cloudrecord'),
        ),
        migrations.AddField(
            model_name='recommendation',
            name='report',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recommendations', to='cost_optimizer.uploadedreport'),
        ),
        migrations.AddField(
            model_name='cloudrecord',
            name='report',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='records', to='cost_optimizer.uploadedreport'),
        ),
        migrations.AddIndex(
            model_name='cloudrecord',
            index=models.Index(fields=['service_name'], name='cloud_recor_service_4ce0dc_idx'),
        ),
        migrations.AddIndex(
            model_name='cloudrecord',
            index=models.Index(fields=['region'], name='cloud_recor_region_4067c5_idx'),
        ),
        migrations.AddIndex(
            model_name='cloudrecord',
            index=models.Index(fields=['resource_name'], name='cloud_recor_resourc_ef6fad_idx'),
        ),
        migrations.AddIndex(
            model_name='cloudrecord',
            index=models.Index(fields=['cost'], name='cloud_recor_cost_4042d2_idx'),
        ),
        migrations.AddIndex(
            model_name='cloudrecord',
            index=models.Index(fields=['utilization_percentage'], name='cloud_recor_utiliza_27dd08_idx'),
        ),
    ]
