# Generated by Django 4.2.7 on 2026-07-22 04:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cost_optimizer', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='uploadedreport',
            name='avg_utilization',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
        migrations.AddField(
            model_name='uploadedreport',
            name='estimated_savings',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='uploadedreport',
            name='highest_cost_service',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='uploadedreport',
            name='total_cost',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='uploadedreport',
            name='total_resources',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='uploadedreport',
            name='total_services',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
